version: '3.7'

networks:
  network:
    ipam:
      driver: default
      config:
      - subnet: ${SV_SUBNET_NETWORK}

services:
  mysql:
    container_name: mysql
    networks:
      network:
        ipv4_address: ${MYSQL_IP}
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
    - ${MYSQL_PORT}:3306
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    - ./mysql/02_init.sh:/docker-entrypoint-initdb.d/02_init.sh
    environment:
    - MYSQL_DATABASE_UT=${MYSQL_DATABASE_UT}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - ADMINISTRATOR_EMAIL=${ADMINISTRATOR_EMAIL}
    - ADMINISTRATOR_FIRST_NAME=${ADMINISTRATOR_FIRST_NAME}
    - ADMINISTRATOR_LAST_NAME=${ADMINISTRATOR_LAST_NAME}
    - ADMINISTRATOR_PHONE_NUMBER=${ADMINISTRATOR_PHONE_NUMBER}
    - APPLICATION_PATH=${APPLICATION}
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
      - INSTALL_GD=${PHP_FPM_INSTALL_GD}
      - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
      - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
      - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
      - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
      - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
      - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
      - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
      - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
      - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
      - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
      - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
      - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
      - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
      - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
      - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
      - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
      dockerfile: Dockerfile
    expose:
    - 9000
    volumes:
    - ${APPLICATION}:/var/www/html
    - ./php-fpm/docker-php-entrypoint.sh:/docker-php-entrypoint.sh
    - .env:/usr/share/envfile:rw
    depends_on:
    - mysql
    networks:
      network:
        ipv4_address: ${PHP_FPM_IP}
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
    - ${APPLICATION}:/var/www/html
    - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    - ./nginx/docker-nginx-entrypoint.sh:/usr/bin/docker-nginx-entrypoint.sh:rw
    - .env:/usr/share/envfile:rw
    ports:
    - ${NGINX_HOST_HTTP_PORT}:80
    - ${NGINX_HOST_HTTPS_PORT}:443
    environment:
    - NGINX_HOST=${NGINX_HOST}
    - APPLICATION_ENV=${APPLICATION_ENV}
    - PRIVATE_LABEL=${PRIVATE_LABEL}
    - CRYPTO_KEY=${CRYPTO_KEY}
    - MAC_KEY=${MAC_KEY}
    - PHP_FPM_IP=${PHP_FPM_IP}
    depends_on:
    - php-fpm
    networks:
      network:
        ipv4_address: ${NGINX_IP}